# Generated by Django 2.0.2 on 2018-08-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Student',
        ),
    ]
