# Generated by Django 2.0.2 on 2018-08-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20180812_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
