# Generated by Django 2.0.2 on 2018-09-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_instrument_studentinstrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
