# Generated by Django 2.0.2 on 2018-09-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20180910_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='activity',
        ),
        migrations.AddField(
            model_name='student',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
