# Generated by Django 2.0.2 on 2018-09-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20180910_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_first_name',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_full_name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_last_name',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
