# Generated by Django 2.0.2 on 2018-09-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_auto_20180910_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_first_name',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_full_name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_last_name',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone_number',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='street',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='street2',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='zipcode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
