# Generated by Django 2.0.2 on 2018-10-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_auto_20180910_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolled',
        ),
        migrations.AddField(
            model_name='student',
            name='date_enrolled',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='student',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_first_name',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_full_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_last_name',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone_number',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='student',
            name='street',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='student',
            name='street2',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='student',
            name='zipcode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
